server.port=8082
spring.application.name=ms-clientes

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.gkcyyzzaizzuglmyetpe}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:GkCMQaTgcoo4ETva}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:smartlogix-secret-key-2024-super-segura-para-produccion-abc123}
jwt.expiration=86400000

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}