apiVersion: v1
kind: Secret
metadata:
  name: smartlogix-secrets
  namespace: smartlogix
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "${SUPABASE_URL}"
  SPRING_DATASOURCE_USERNAME: "${SUPABASE_USERNAME}"
  SPRING_DATASOURCE_PASSWORD: "${SUPABASE_PASSWORD}"
  JWT_SECRET: "${JWT_SECRET}"
  RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"
